### ISSUE TITLE
Class 'Nahid\Hookr\HookrServiceProvider' not found

### ISSUE THREAD

**Issue by mprince2k18** [nahid/hookr#1]
Hello, vaia,

I want to use this package. But there has no ServiceProvider. facing this error: Class 'Nahid\Hookr\HookrServiceProvider' not found

Thank you

**Comment by nahid** [comment]
Hello @mprince2k18 ,
Thank you for using Hookr. There are no need to use service provider for this project. Here we use the static features to develop singleton.

**Comment by mprince2k18** [comment]
> Hello @mprince2k18 ,
> Thank you for using Hookr. There are no need to use service provider for this project. Here we use the static features to develop singleton.

But I tried to use it in Laravel 8. It's installed without any warning and I did everything that was written in the readme.md documentation.
